name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened]

jobs:
  add-reviewers:
    runs-on: ubuntu-latest
    steps:
          # Checkout the repository so we can interact with it
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      - name: Get All Contributors
        id: contributors
        run: |
          contributors=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/contributors" | jq -r '.[].login')
          echo "contributors=${contributors}" >> $GITHUB_ENV

      - name: Request Review from Contributors
        run: |
          for user in $contributors; do
            gh pr edit --add-reviewer "$user"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}